server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes: 
        - id: ms-inventory
          uri: lb://ms-inventory
          predicates:
            - Path=/api/productos/**

        - id: ms-sales
          uri: lb://ms-sales
          predicates:
            - Path=/api/ventas/**
    
        - id: ms-clients
          uri: lb://ms-clients
          predicates:
            - Path=/api/clientes/**
      
        - id: ms-reports
          uri: lb://ms-reports
          predicates:
            - Path=/api/reportes/**
      
        - id: ms-providers
          uri: lb://ms-providers
          predicates:
            - Path=/api/proveedores/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG